### ISSUE TITLE
Hang while querying a Postgres database on node@14

### ISSUE THREAD

**Issue by visnup** [observablehq/database-proxy#21]
To reproduce:
1. Install node@14
2. Follow setup instructions to proxy to a local Postgres database
3. Run a query against the local database
4. See the cell hang

While debugging this issue, it seems like the pool never successfully connects to the database and never returns a response, hanging the cell. Upgrading pg to latest (8.6.0) seems to fix this issue.

See also https://github.com/observablehq/feedback/issues/121

**Comment by john-guerra** [comment]
I was about to submit a PR for this. Yes, upgrading pg to 8 worked for me as well

**Comment by visnup** [comment]
> I was about to submit a PR for this. Yes, upgrading pg to 8 worked for me as well

PR is at #23 but I wanted to test it more to make sure TLS options work.

**Comment by visnup** [comment]
Just released v2 which should fix this.
